### ISSUE TITLE
Fatal: deltaDays on Settings.py set to a value bigger than current dataset.

### ISSUE THREAD

**Issue by hugokoopmans** [Gab0/japonicus#107]
Hi,

I do not understand how this error arises...
I have more then 2 months of candlestick data. 
Sometimes it runs for a lot of epochs but almost always at some stage this error occurs...

deltaDays is set to 10 days

in the dataset options i have:

        'dataset' : {
            # -- Gekko Dataset Settings
            # leave the ! on the ignored entry as convenient;
            '!dataset_source': None,
             # dataset_source can be set to None so it searches from any source;
            'dataset_source': { # in case of specifying exchange-currency-asset, rename this removing the '!', and del the original key above.
                "exchange": "kraken",
                "currency": 'EUR',
                "asset": 'ETH',
            },
            'eval_dataset_source': None,

            # span in days from the end of dataset to the beggining. Or zero.
            # (to restrain length);
            'dataset_span': 14,
            'eval_dataset_span': 7

            }

As i do not want to use all of the data each time in the backtest... but I can never finish a run now ...

Please explain a bit more how the datasets are chosen to backtest and evaluate?

Also I do not understand what Locale1 and Locale2 are actually doing? Are those two seperate runs of backtests?

**Comment by Gab0** [comment]
The error comes at EPOCH 20? You restrained evaluation dataset that comes into scene at that epoch to seven days, thats less than 10 deltaDays so gives error. I mean, due to that an error is guaranteed at EPOCH 20 XD but if its on the start plz report here.

japonicus is a parallel GA, locale1 and locale2 are different populations that evolve on different candlesticks.

cheers!

**Comment by hugokoopmans** [comment]
ok now i am confused, it would be nice to have a small explanation on the structure japonicus uses.
Locale1 and 2 are different candlestick size? where do i set the value of those? can I do more then two at the same time? 

Also unclear to me how the date ranges are selected over the available candles in the database.

Also I do not understand/and there is no documentation on, the backtest and evaluation scheme that is used...

So we have dataset_source, eval_dataset_source, dataset_span and eval_dataset_span and 
deltaDays and evaluateSettingsPeriodically' elsewhere in the settings file.
How does it all work together?
When is what dataset used?

My usecase: I trade ETH/EUR I want to find a strat with parameters fit to the last say 14 days so I am close to the market. I have 2 months of minute data in the database. What is the difference between the dataset and de evaluation dataset?

I would love to write up some documentation but i need to understand how it works for myself first...

**Comment by Gab0** [comment]
Would be really nice to have a contributor writing about the workings of this app, as a proof that its actually understanable XD. The present documentation was actually very informative for the earliers versions but since a lot of strange stuff have been added ;]

Locale1 and 2 are diferent time ranges for the only evaluation dataset. They have same size of `deltaDays`.
The evaluation dataset is a dataset that is different from evolution dataset (XD), and its purpose is to check the general overfitting of current parameters as a blind test i.e. if it does good on dataset it has evolved on, but do crap in another dataset, we may have a problem..
The new interface is more organized and should answer your other questions...

**Comment by Gab0** [comment]
lulz actually I was wrong on the first answer. We need those docs XD. 
So did you solve the problem?

**Comment by hugokoopmans** [comment]
You were right, after changing the evaluation_dataset to > then deltaDays it runs fine .
